#!/usr/bin/env node

var fs = require('fs')
var path = require('path')
var bulk = require('bulk-require')
var d3 = require('d3-geo-projection')
var projections = bulk(__dirname, ['projections/world/*.js']).projections

// country-level geojsons
fs.readFile(path.join(__dirname, 'data/countries.geojson'), function (err, data) {
  if (err) { throw err }
  data = JSON.parse(data)
  write(data, projections.world)
})

// country-level geojsons
fs.readFile(path.join(__dirname, 'data/us-states.geojson'), function (err, data) {
  if (err) { throw err }
  data = JSON.parse(data)
  write(data, projections.us)
})

function write (data, projections) {
  for (var projection in projections) {
    if (typeof projections[projection] !== 'function') {
      throw new Error (projection + ' is not a valid projection')
    }
    var out = path.join(__dirname, 'output/geojson', projection + '.geojson')
    fs.writeFile(out, JSON.stringify(d3.geoProject(data, projections[projection])), (err) => {
      if (err) { throw err }
    })
  }
}
