#!/usr/bin/env node

var geojsonStream = require('geojson-stream')
var extent = require('turf-extent')
var through = require('through2')
var argv = require('minimist')(process.argv.slice(2))

var ALBERS_USA = require('./projections/albers-usa')
var MERCATOR = require('./projections/mercator')

var proj
if (!argv.projection || argv.projection === 'albersUsa') {
  proj = ALBERS_USA
} else if (argv.projection === 'mercator') {
  proj = MERCATOR
} else {
  throw new Error('Unsupported projection ' + argv.projection)
}

process.stdin.pipe(geojsonStream.parse())
.pipe(through.obj(write))
.pipe(geojsonStream.stringify())
.pipe(process.stdout)

function write (feature, _, next) {
  reproject(feature.geometry.coordinates)
  feature.bbox = extent(feature)
  this.push(feature)
  next()
}

function forward (coordinates) {
  var projected = proj(coordinates)
  if (!projected) {
    coordinates[0] = coordinates[1] = null
    return false
  }
  coordinates[0] = projected[0]
  coordinates[1] = -projected[1]
  return true
}

function reverse (projected) {
  projected[1] = -projected[1]
  var reversed = proj.invert(projected)
  if (!reversed) {
    projected[0] = projected[1] = null
    return false
  }
  projected[0] = reversed[0]
  projected[1] = reversed[1]
  return true
}

